# Generated by Django 4.2.1 on 2023-07-14 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='fecha de edicion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='redsocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('icono', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicacion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizado')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('categories', models.ManyToManyField(to='core.category', verbose_name='categorias')),
            ],
            options={
                'verbose_name': 'Redsocial',
                'verbose_name_plural': 'Redsociales',
                'ordering': ['-created'],
            },
        ),
    ]
