# Generated by Django 4.2.1 on 2023-07-14 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iconos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('icono', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicacion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizado')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'Icono',
                'verbose_name_plural': 'Iconos',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='redsocial',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='redsocial',
            name='categories',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='redsocial',
        ),
    ]
