# Generated by Django 4.2.1 on 2023-07-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
