# Generated by Django 4.2.3 on 2023-08-16 20:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='contenido')),
                ('orden', models.SmallIntegerField(default=0, verbose_name='order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='fecha de edicion')),
            ],
            options={
                'verbose_name': 'Pàgina',
                'verbose_name_plural': 'Pàginas',
                'ordering': ['-created'],
            },
        ),
    ]
