# Generated by Django 4.2 on 2023-08-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagina'),
        ('portafolio', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='project',
        ),
    ]
