# Generated by Django 4.2.1 on 2023-09-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='Pedido',
            new_name='pedido',
        ),
    ]
