# Generated by Django 4.2 on 2023-09-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
