# Generated by Django 4.2.1 on 2023-07-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='image',
            field=models.ImageField(upload_to='Servicio', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='price',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='precio'),
        ),
    ]
